#!/usr/bin/env python3
"""Generate a Markdown index from data/artifacts/*.yml.

The generated file is intentionally separate from the manually curated
docs/artifacts/index.md page. This keeps narrative structure hand-written while
still making the YAML data visible and reviewable in the site.
"""

from __future__ import annotations

from pathlib import Path
import sys

try:
    import yaml
except ImportError:
    print("Install PyYAML to use this script: pip install pyyaml", file=sys.stderr)
    raise SystemExit(1)


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data" / "artifacts"
DOCS_ARTIFACTS_DIR = ROOT / "docs" / "artifacts"
OUTPUT_PATH = DOCS_ARTIFACTS_DIR / "generated-index.md"

CATEGORY_LABELS = {
    "Persistence": "持久化",
    "Autoruns": "自启动",
    "Execution": "程序执行",
    "ProgramPresence": "程序存在",
    "ProgramMetadata": "程序元数据",
    "UserActivity": "用户行为",
    "USB": "USB",
    "Device": "设备",
    "Volume": "卷 / 盘符",
    "RDP": "RDP",
    "RemoteAccess": "远程访问",
    "SecurityPolicy": "安全策略",
    "Accounts": "账户",
    "UserProfiles": "用户配置文件",
    "Firewall": "防火墙",
    "UAC": "UAC",
    "AuditPolicy": "审计策略",
    "Defender": "Defender",
    "CredentialAccess": "凭据访问",
    "Hijacking": "劫持",
    "Shell": "Shell",
    "ComDlg32": "ComDlg32",
    "Services": "服务",
}

VALUE_LABELS = {
    "High": "高",
    "Medium": "中",
    "Low": "低",
}


def as_list(value: object) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item) for item in value if item is not None]
    return [str(value)]


def md_escape(value: object) -> str:
    text = str(value or "")
    return text.replace("|", "\\|").replace("\n", " ")


def code(value: object) -> str:
    text = md_escape(value)
    if not text:
        return ""
    return f"`{text.replace('`', '\\`')}`"


def join_text(values: object) -> str:
    return ", ".join(md_escape(item) for item in as_list(values))


def display_category(values: object) -> str:
    return ", ".join(CATEGORY_LABELS.get(item, item) for item in as_list(values))


def display_value(value: object) -> str:
    text = md_escape(value)
    return VALUE_LABELS.get(text, text)


def join_code(values: object) -> str:
    return ", ".join(code(item) for item in as_list(values))


def find_doc_path(item: dict[str, object], data_path: Path) -> str:
    artifact_id = str(item.get("id") or data_path.stem)
    matches = sorted(DOCS_ARTIFACTS_DIR.rglob(f"{artifact_id}.md"))
    if not matches:
        return md_escape(item.get("title") or artifact_id)
    rel = matches[0].relative_to(DOCS_ARTIFACTS_DIR)
    title = md_escape(item.get("title") or artifact_id)
    return f"[{title}]({rel.as_posix()})"


def format_path_entry(entry: object) -> str:
    if not isinstance(entry, dict):
        return code(entry)

    parts: list[str] = []
    root = entry.get("root") or entry.get("hive")
    path = entry.get("path")
    value = entry.get("value")

    if root and path:
        parts.append(f"{root}\\{path}")
    elif path:
        parts.append(str(path))

    if value:
        parts.append(f"/v {value}")

    if not parts:
        return ""
    return code(" ".join(parts))


def primary_paths(paths: object, limit: int = 2) -> str:
    entries = as_list(paths) if not isinstance(paths, list) else paths
    formatted = [format_path_entry(entry) for entry in entries[:limit]]
    formatted = [item for item in formatted if item]
    if not formatted:
        return ""
    suffix = "<br>..." if len(entries) > limit else ""
    return "<br>".join(formatted) + suffix


def load_items() -> list[tuple[Path, dict[str, object]]]:
    items: list[tuple[Path, dict[str, object]]] = []
    for path in sorted(DATA_DIR.glob("*.yml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if not isinstance(data, dict):
            raise ValueError(f"{path} does not contain a YAML mapping")
        items.append((path, data))
    return sorted(items, key=lambda pair: str(pair[1].get("title") or pair[0].stem).lower())


def build_markdown(items: list[tuple[Path, dict[str, object]]]) -> str:
    lines = [
        "# 结构化数据索引",
        "",
        "<!-- This file is generated by scripts/generate-artifact-index.py. Do not edit manually. -->",
        "",
        "本页由 `data/artifacts/*.yml` 生成。人工维护的叙事索引见 [注册表 Artifact](index.md)。",
        "",
        "| Artifact | 分类 | 原生根键 | Hive / 离线文件 | 证据类型 | 取证价值 | 检测价值 | 主要路径 |",
        "|---|---|---|---|---|---|---|---|",
    ]

    for path, item in items:
        artifact = find_doc_path(item, path)
        category = display_category(item.get("category"))
        native_root = code(item.get("native_root"))
        hive_values = as_list(item.get("hive"))
        offline_values = as_list(item.get("offline_file"))
        hive_offline = "<br>".join(filter(None, [join_code(hive_values), join_code(offline_values)]))
        evidence_type = join_text(item.get("evidence_type") or item.get("artifact_type"))
        forensic_value = display_value(item.get("forensic_value"))
        detection_value = display_value(item.get("detection_value"))
        paths = primary_paths(item.get("paths"))

        lines.append(
            f"| {artifact} | {category} | {native_root} | {hive_offline} | "
            f"{evidence_type} | {forensic_value} | {detection_value} | {paths} |"
        )

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    items = load_items()
    markdown = build_markdown(items)
    OUTPUT_PATH.write_text(markdown, encoding="utf-8")
    print(markdown)
    print(f"\nGenerated {OUTPUT_PATH.relative_to(ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
