#!/usr/bin/env python3
"""Generate registry-tree structured index pages from data/registry/*.yml."""

from __future__ import annotations

from collections import defaultdict
import os
from pathlib import Path
import sys

try:
    import yaml
except ImportError:
    print("Install PyYAML to use this script: pip install pyyaml", file=sys.stderr)
    raise SystemExit(1)


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data" / "registry"
DOCS_DIR = ROOT / "docs"
REGISTRY_TREE_DIR = DOCS_DIR / "registry-tree"
GENERATED_INDEX = REGISTRY_TREE_DIR / "generated-index.md"
COVERAGE = REGISTRY_TREE_DIR / "coverage.md"

REQUIRED_FIELDS = ("id", "title", "native_paths", "root", "hive")
STATUS_LABELS = {
    "draft": "草稿",
    "reviewed": "已审阅",
    "stable": "稳定",
}
CONFIDENCE_LABELS = {
    "low": "低",
    "medium": "中",
    "high": "高",
}


def as_list(value: object) -> list[object]:
    if value is None:
        return []
    if isinstance(value, list):
        return [item for item in value if item is not None]
    return [value]


def as_text_list(value: object) -> list[str]:
    return [str(item) for item in as_list(value)]


def md_escape(value: object) -> str:
    return str(value or "").replace("|", "\\|").replace("\n", " ")


def code(value: object) -> str:
    text = md_escape(value)
    if not text:
        return ""
    return f"`{text.replace('`', '\\`')}`"


def rel_doc(path: str | object) -> str:
    return str(path or "").replace("\\", "/")


def link_to_doc(label: object, path: object, from_dir: Path = REGISTRY_TREE_DIR) -> str:
    text = md_escape(label)
    rel_path = rel_doc(path)
    if not rel_path:
        return text
    target = ROOT / rel_path
    href = os.path.relpath(target, start=from_dir).replace(os.sep, "/")
    return f"[{text}]({href})"


def first_path(item: dict[str, object]) -> str:
    paths = as_text_list(item.get("native_paths"))
    return paths[0] if paths else ""


def topics(item: dict[str, object]) -> str:
    return " ".join(f'<span class="ww-chip ww-chip--topic">{md_escape(topic)}</span>' for topic in as_text_list(item.get("topics")))


def scenario_links(item: dict[str, object]) -> str:
    links: list[str] = []
    for scenario in as_list(item.get("related_scenarios")):
        if isinstance(scenario, dict):
            links.append(link_to_doc(scenario.get("title"), scenario.get("path")))
        else:
            links.append(md_escape(scenario))
    return "<br>".join(links)


def load_entries() -> tuple[list[dict[str, object]], list[str]]:
    entries: list[dict[str, object]] = []
    warnings: list[str] = []
    seen_ids: set[str] = set()

    for path in sorted(DATA_DIR.glob("*.yml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if not isinstance(data, dict):
            raise ValueError(f"{path} does not contain a YAML mapping")

        for field in REQUIRED_FIELDS:
            if not data.get(field):
                raise ValueError(f"{path.relative_to(ROOT)} missing required field: {field}")

        entry_id = str(data["id"])
        if entry_id in seen_ids:
            raise ValueError(f"Duplicate registry entry id: {entry_id}")
        seen_ids.add(entry_id)

        page = data.get("page")
        if page:
            page_path = ROOT / rel_doc(page)
            if not page_path.exists():
                raise ValueError(f"{path.relative_to(ROOT)} references missing page: {page}")

        for scenario in as_list(data.get("related_scenarios")):
            if isinstance(scenario, dict) and scenario.get("path"):
                scenario_path = ROOT / rel_doc(scenario["path"])
                if not scenario_path.exists():
                    warnings.append(f"{path.relative_to(ROOT)} references missing scenario: {scenario['path']}")

        entries.append(data)

    return sorted(entries, key=lambda item: (str(item.get("root")), str(item.get("hive")), first_path(item))), warnings


def build_generated_index(entries: list[dict[str, object]]) -> str:
    lines = [
        "# 结构化注册表索引",
        "",
        "<!-- This file is generated by scripts/generate-registry-index.py. Do not edit manually. -->",
        "",
        "本页由 `data/registry/*.yml` 生成，面向读者提供结构化路径入口。注册表位置正文仍由人工维护。",
        "",
    ]

    by_hive: dict[str, list[dict[str, object]]] = defaultdict(list)
    for item in entries:
        by_hive[str(item.get("hive"))].append(item)

    for hive in sorted(by_hive):
        lines.extend([f"## {md_escape(hive)}", ""])
        lines.extend([
            "| 路径 | 简述 | Root | 主题 | 页面 | 相关场景 |",
            "|---|---|---|---|---|---|",
        ])
        for item in by_hive[hive]:
            path_text = "<br>".join(code(path) for path in as_text_list(item.get("native_paths"))[:2])
            summary = md_escape(item.get("summary"))
            page = link_to_doc(item.get("title"), item.get("page"))
            lines.append(
                f"| {path_text} | {summary} | {code(item.get('root'))} | "
                f"{topics(item)} | {page} | {scenario_links(item)} |"
            )
        lines.append("")

    by_topic: dict[str, list[dict[str, object]]] = defaultdict(list)
    for item in entries:
        for topic in as_text_list(item.get("topics")):
            by_topic[topic].append(item)

    lines.extend(["## 按主题", ""])
    lines.extend(["| 主题 | 路径 | Hive | 页面 |", "|---|---|---|---|"])
    for topic in sorted(by_topic):
        paths = "<br>".join(code(first_path(item)) for item in by_topic[topic])
        pages = "<br>".join(link_to_doc(item.get("title"), item.get("page")) for item in by_topic[topic])
        hives = "<br>".join(code(item.get("hive")) for item in by_topic[topic])
        lines.append(f"| {md_escape(topic)} | {paths} | {hives} | {pages} |")

    lines.append("")
    return "\n".join(lines)


def build_coverage(entries: list[dict[str, object]]) -> str:
    lines = [
        "# 注册表位置覆盖矩阵",
        "",
        "<!-- This file is generated by scripts/generate-registry-index.py. Do not edit manually. -->",
        "",
        "本页由 `data/registry/*.yml` 生成，用于维护当前结构化覆盖范围。它不是完整 Windows 注册表清单。",
        "",
        "## 状态说明",
        "",
        "| 状态 | 含义 |",
        "|---|---|",
        "| 草稿 | 已有数据，但字段、引用或页面结构仍需审阅。 |",
        "| 已审阅 | 主要字段已核对，仍可能继续补参考或版本差异。 |",
        "| 稳定 | 当前事实层可作为后续索引和互链基础。 |",
        "",
    ]

    by_root_hive: dict[tuple[str, str], list[dict[str, object]]] = defaultdict(list)
    for item in entries:
        by_root_hive[(str(item.get("root")), str(item.get("hive")))].append(item)

    for root, hive in sorted(by_root_hive):
        lines.extend([f"## {md_escape(root)} / {md_escape(hive)}", ""])
        lines.extend([
            "| 注册表路径 | 页面 | Root | Hive | 主题 | 相关场景 | 状态 | 备注 |",
            "|---|---|---|---|---|---|---|---|",
        ])
        for item in by_root_hive[(root, hive)]:
            status = STATUS_LABELS.get(str(item.get("status")), md_escape(item.get("status")))
            confidence = CONFIDENCE_LABELS.get(str(item.get("confidence")), md_escape(item.get("confidence")))
            page = link_to_doc(item.get("title"), item.get("page"))
            note = f"资料把握：{confidence}"
            lines.append(
                f"| {code(first_path(item))} | {page} | {code(root)} | {code(hive)} | "
                f"{topics(item)} | {scenario_links(item)} | {status} | {note} |"
            )
        lines.append("")

    lines.extend([
        "## 下一阶段候选",
        "",
        "| 注册表路径 | 状态 | 主题 | 相关场景 | 备注 |",
        "|---|---|---|---|---|",
        "| `HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System` | 待新增 | 策略 | 安全策略与防护配置 | 用户级系统策略。 |",
        "| `HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Attachments` | 待新增 | 策略 / 用户行为 | 反取证与清理痕迹 | Attachment Manager。 |",
        "| `HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Associations` | 待新增 | 策略 / Shell | Shell / Explorer 用户行为 | 文件关联策略。 |",
        "| `HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced` | 待新增 | 用户行为 / Shell | Shell / Explorer 用户行为 | Explorer 显示和行为偏好。 |",
        "| `HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\TypedPaths` | 待新增 | 用户行为 | Shell / Explorer 用户行为 | Explorer 地址栏输入历史。 |",
        "| `HKCU\\Software\\Microsoft\\Windows\\Shell\\BagMRU` | 待新增 | 用户行为 | Shell / Explorer 用户行为 | ShellBags。 |",
        "| `HKLM\\SYSTEM\\ControlSet00x\\Enum\\STORAGE` | 待新增 | 设备 | USB 与外接设备 | 存储设备枚举。 |",
        "| `HKLM\\SYSTEM\\ControlSet00x\\Control\\DeviceContainers` | 待新增 | 设备 | USB 与外接设备 | 设备容器关联。 |",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    entries, warnings = load_entries()
    GENERATED_INDEX.write_text(build_generated_index(entries), encoding="utf-8")
    COVERAGE.write_text(build_coverage(entries), encoding="utf-8")

    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)

    print(
        f"Generated {len(entries)} registry entries into "
        f"{GENERATED_INDEX.relative_to(ROOT)} and {COVERAGE.relative_to(ROOT)}"
    )


if __name__ == "__main__":
    main()
